name: Application CI

on:
  pull_request:
    branches: [ master, staging ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env.example to .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Up container
        run: docker-compose up -d
      - name: PHPUnit
        run: docker-compose exec - T backend bash -lc './vendor/bin/phpunit'
