name: Application CI

on:
  pull_request:
    branches: [ master, staging ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env.example to .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker-compose exec backend bash -lc './vendor/bin/phpunit
